import Vue from 'vue'
import { NavBar, Tabbar, TabbarItem, Toast, Search, Swipe, SwipeItem, grid, GridItem, Lazyload, Icon, Sidebar, SidebarItem, Image, Loading, GoodsAction, GoodsActionIcon, GoodsActionButton, Rate, ActionSheet, Stepper, Dialog, Checkbox, CheckboxGroup } from 'vant'

Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(grid)
Vue.use(GridItem)
Vue.use(Lazyload)
Vue.use(Icon)
Vue.use(Sidebar)
Vue.use(SidebarItem)
Vue.use(Image)
Vue.use(GoodsAction)
Vue.use(GoodsActionIcon)
Vue.use(GoodsActionButton)
Vue.use(Rate)
Vue.use(Loading)
Vue.use(ActionSheet)
Vue.use(Stepper)
Vue.use(Dialog)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
